import { roboto } from '@/app/ui/styles/mui.theme';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import AppProvider from '@/app/provider/AppProvider';
import ClientIntlProvider from '@/app/provider/ClientIntlProvider';
import { getLocale, getMessages } from 'next-intl/server';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';

export const metadata: Metadata = {
  title: 'DER-EMS',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} className={roboto.variable} suppressHydrationWarning>
      <body>
        <InitColorSchemeScript attribute=".mui-theme-%s" />
        {/* <ClientIntlProvider initialLocale={locale} initialMessages={messages} /> */}
        <NextIntlClientProvider>
          <AppProvider>{children}</AppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
