import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { roboto } from '@/app/ui/styles/mui.theme';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import AppProvider from '@/app/provider/AppProvider';
// import { cookies } from 'next/headers';
// import { AppLocale, loadMessages } from '@/shared/i18n/loadMessages';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'DER-EMS',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  // const messages = await loadMessages(locale);
  // const messages = (await import(`../../locales/${locale}.json`)).default;
  return (
    <html lang={locale} className={roboto.variable} suppressHydrationWarning>
      <body>
        <InitColorSchemeScript attribute=".mui-theme-%s" />
        <NextIntlClientProvider>
          <AppProvider>{children}</AppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
