import type { Metadata } from "next";
// import "./globals.css";
import { roboto } from "@/shared/app/styles/mui.theme";
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript";
import AppProvider from "@/shared/app/provider/AppProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable} suppressHydrationWarning>
      <body>
        <InitColorSchemeScript attribute=".mui-theme-%s" />
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
